In [1]:
text = """
The sun was shining brightly in the clear blue sky, and a gentle breeze rustled the leaves of the tall trees. People were out enjoying the beautiful weather, some sitting in the park, others taking a leisurely stroll along the riverbank. Children were playing games, and laughter filled the air.

As the day turned into evening, the temperature started to drop, and the sky transformed into a canvas of vibrant colors. Families gathered for picnics, and the smell of barbecues wafted through the air. It was a perfect day for a picnic by the lake.

In the distance, you could hear the sound of live music coming from a local band, and people began to gather around the stage to enjoy the performance. The atmosphere was electric, and the music had everyone swaying to the beat.

As the stars began to twinkle in the night sky, the crowd grew even larger, and the festivities continued well into the night. It was a day filled with joy, laughter, and memories that would last a lifetime.

The ancient castle stood on a hill, its towering spires reaching up towards the sky. The castle had a rich history, and its stone walls had witnessed countless battles and royal intrigues. Tourists from all over the world flocked to explore its mysteries.

Inside the castle, you could find grand halls adorned with magnificent tapestries and chandeliers. The air was thick with the scent of history, and the creaking of old wooden floors echoed in the corridors. The castle's library housed an impressive collection of books, some dating back centuries.

As you ventured further into the castle, you would discover hidden chambers and secret passages. Legends spoke of a hidden treasure buried somewhere within its walls, waiting to be found by a brave adventurer.

Outside the castle, a vast moat surrounded it, and a drawbridge provided access to the outside world. Beyond the moat, a lush forest stretched as far as the eye could see, inviting exploration and adventure.

The village at the base of the hill relied on the castle for protection and trade. The townspeople were friendly and welcoming, and their stories were filled with folklore and local legends.

At night, the castle's windows lit up with a warm, inviting glow, making it look like something out of a fairy tale. It was a place where history and fantasy intertwined, a place where dreams and reality converged.

In the heart of the bustling city, the streets were alive with the sounds of traffic and the chatter of people going about their daily lives. Skyscrapers reached towards the heavens, their glass facades reflecting the vibrant energy of the metropolis.

Street vendors sold a variety of goods, from sizzling hot dogs to handmade jewelry. The aroma of freshly brewed coffee wafted from the corner cafes, where patrons sipped their drinks while watching the world go by.

Amid the urban chaos, a beautiful park provided a serene escape. Tall trees offered shade, and a tranquil pond was home to ducks and swans. The park's paths were lined with benches where people could sit and read, or simply enjoy the calm in the midst of the urban storm.

The city's cultural scene was rich and diverse, with theaters showcasing the latest plays and art galleries displaying works from local and international artists. The symphony orchestra filled the air with music, and museums held treasures from various eras.
"""

In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts([text])

In [6]:
len(tokenizer.word_index)

308

In [7]:
input_seq = []
for sentence in text.split('.'):
    tokenized_sent = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sent)):
        input_seq.append(tokenized_sent[:i+1])

In [ ]:
input_seq

In [81]:
max_len = 28

In [82]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

pad_input_seq = pad_sequences(input_seq , maxlen=max_len , padding='pre')

In [83]:
pad_input_seq

array([[  0,   0,   0, ...,   0,   1,  61],
       [  0,   0,   0, ...,   1,  61,   7],
       [  0,   0,   0, ...,  61,   7,  62],
       ...,
       [  0,   0,   0, ..., 305, 306,  10],
       [  0,   0,   0, ..., 306,  10, 307],
       [  0,   0,   0, ...,  10, 307, 308]])

In [84]:
X = pad_input_seq[:,:-1] #removing last element 
X

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,  61],
       [  0,   0,   0, ...,   1,  61,   7],
       ...,
       [  0,   0,   0, ..., 304, 305, 306],
       [  0,   0,   0, ..., 305, 306,  10],
       [  0,   0,   0, ..., 306,  10, 307]])

In [85]:
y = pad_input_seq[:,-1] #all last elements
y

array([ 61,   7,  62,  63,   8,   1,  64,  65,  14,   2,   3,  66,  67,
        68,   1,  69,   4,   1,  33,  34,   9,  35,  70,   1,  36,  71,
        37,  72,   8,   1,  38,  73,  74,   3,  75,  76,  77,   1,  78,
         9,  80,  81,   2,  39,  16,   1,  17,   1,  24,  82,  18,  83,
         1,  84,  85,   5,  86,   2,   1,  14,  87,  18,   3,  88,   4,
        40,  89,  91,  25,  92,   2,   1,  93,   4,  94,  41,  95,   1,
        17,   7,   3,  96,  24,  25,   3,  97,  26,   1,  98,   1,  99,
        19,  20, 100,   1, 101,   4, 102,  27, 103,  10,   3,  28, 104,
         2,  15,  42,   5, 105, 106,   1, 107,   5,  43,   1, 108, 109,
         7, 110,   2,   1,  27,  29, 111, 112,   5,   1, 113,   1, 114,
        42,   5, 115,   8,   1,  30,  14,   1, 116, 117, 118, 119,   2,
         1, 120, 121, 122,  18,   1,  30,   7,   3,  24,  16,   6, 123,
        39,   2, 124, 125,  44, 126,   3, 127, 128,  11, 129,  45,   3,
        46,  21, 130, 131, 132,  47,  48,   1,  14,  11,  29,   

In [86]:
X.shape

(536, 27)

In [87]:
y.shape

(536,)

In [88]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y , num_classes = 335)

In [89]:
y.shape

(536, 335)

In [90]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , LSTM , Dense

In [95]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(335, 100, input_length=28, trainable=True))
model.add(LSTM(150, input_shape=(28, 100)))
model.add(Dense(335, activation='softmax'))
model.build((None, 28))  # or add a sample input shape here
model.summary()



Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 28, 100)        │        33,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 335)            │        50,585 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 234,685 (916.74 KB)

 Trainable params: 234,685 (916.74 KB)

 Non-trainable params: 0 (0.00 B)

In [96]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=100)

In [ ]:
train_text = "The ancient castle"

for i in range(15):
#tokenize
    token_text = tokenizer.texts_to_sequences([train_text])[0]

#padding
    padded_token_input = pad_sequences([token_text] , maxlen=28 , padding='pre')

#predict
    pos = np.argmax(model.predict(padded_token_input))

    for word,index in tokenizer.word_index.items():
        if index==pos:
            train_text = train_text + " " + word
            print(train_text)


In [106]:
import numpy as np